### ISSUE TITLE
why minimum-stability dev?

### ISSUE THREAD

**Issue by garak** [FastFeed/FastFeed#28]

**Comment by peter279k** [comment]
It's still work on development so the minimum stability is `dev` :).

**Comment by garak** [comment]
I don't get you. The `minimum-stability` option is about your vendors, not about your own project.
Which of your vendors is needed on `dev-master`?

**Comment by peter279k** [comment]
@garak, that's right.

I think it should change into the `stable`.

**Comment by peter279k** [comment]
Resolves this issue via PR #34.
