### ISSUE TITLE
Is there enclosure for mp3, mp4 images ect ? 

### ISSUE THREAD

**Issue by onigetoc** [FastFeed/FastFeed#31]
Is there enclosure option or way to get mp3, mp4 images enclosures ?

also: get type and lenght

I tryed : 

```
let extension = this._extractExtension(item, 'enclosure:');
    if (extension.attributes) {
      return extension.attributes.url;
    }
 }
```

**Comment by desarrolla2** [comment]
Looks like your code is javascript, but FastFeed is written on PHP
